fix typo

diff --git a/.github/workflows/test2.yaml b/.github/workflows/test2.yaml
--- a/.github/workflows/test2.yaml
+++ b/.github/workflows/test2.yaml
@@ -175,7 +175,7 @@ jobs:
             echo > "up/${prefix}-hash.txt"
             sha256sum "$file" >> "up/${prefix}-hash.txt"
             cp -a "$file" "up/$new_filename"
-            curl -u "${{ secrets.AP }}" -T "up/$new_filename" "${{ secrets.ALN_URL }}" || echo "Upload of $new_filename failed
+            curl -u "${{ secrets.AP }}" -T "up/$new_filename" "${{ secrets.ALN_URL }}" || echo "Upload of $new_filename failed"
             curl -u "${{ secrets.AP }}" -T "up/${prefix}-hash.txt" "${{ secrets.ALN_URL }}" || echo "Upload of ${prefix}-hash.txt failed"
           fi
         done
